/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSpacesRouteImport } from './routes/_authenticated/spaces'
import { Route as AuthenticatedSpacesSpaceIdRouteImport } from './routes/_authenticated/spaces_.$spaceId'
import { Route as AuthenticatedInvitesInviteIdRouteImport } from './routes/_authenticated/invites.$inviteId'
import { Route as AuthenticatedSpacesSpaceIdIndexRouteImport } from './routes/_authenticated/spaces_.$spaceId.index'
import { Route as AuthenticatedSpacesSpaceIdPostsRouteImport } from './routes/_authenticated/spaces_.$spaceId.posts'
import { Route as AuthenticatedSpacesSpaceIdPetsRouteImport } from './routes/_authenticated/spaces_.$spaceId.pets'
import { Route as AuthenticatedSpacesSpaceIdMembersRouteImport } from './routes/_authenticated/spaces_.$spaceId.members'
import { Route as AuthenticatedSpacesSpaceIdInvitesRouteImport } from './routes/_authenticated/spaces_.$spaceId.invites'
import { Route as AuthenticatedSpacesSpaceIdPostsNewRouteImport } from './routes/_authenticated/spaces_.$spaceId.posts_.new'
import { Route as AuthenticatedSpacesSpaceIdPostsPostIdRouteImport } from './routes/_authenticated/spaces_.$spaceId.posts_.$postId'
import { Route as AuthenticatedSpacesSpaceIdPetsPetIdRouteImport } from './routes/_authenticated/spaces_.$spaceId.pets_.$petId'
import { Route as AuthenticatedSpacesSpaceIdPostsPostIdEditRouteImport } from './routes/_authenticated/spaces_.$spaceId.posts_.$postId.edit'
import { Route as AuthenticatedSpacesSpaceIdPetsPetIdEditRouteImport } from './routes/_authenticated/spaces_.$spaceId.pets_.$petId_.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSpacesRoute = AuthenticatedSpacesRouteImport.update({
  id: '/spaces',
  path: '/spaces',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSpacesSpaceIdRoute =
  AuthenticatedSpacesSpaceIdRouteImport.update({
    id: '/spaces_/$spaceId',
    path: '/spaces/$spaceId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInvitesInviteIdRoute =
  AuthenticatedInvitesInviteIdRouteImport.update({
    id: '/invites/$inviteId',
    path: '/invites/$inviteId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSpacesSpaceIdIndexRoute =
  AuthenticatedSpacesSpaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSpacesSpaceIdRoute,
  } as any)
const AuthenticatedSpacesSpaceIdPostsRoute =
  AuthenticatedSpacesSpaceIdPostsRouteImport.update({
    id: '/posts',
    path: '/posts',
    getParentRoute: () => AuthenticatedSpacesSpaceIdRoute,
  } as any)
const AuthenticatedSpacesSpaceIdPetsRoute =
  AuthenticatedSpacesSpaceIdPetsRouteImport.update({
    id: '/pets',
    path: '/pets',
    getParentRoute: () => AuthenticatedSpacesSpaceIdRoute,
  } as any)
const AuthenticatedSpacesSpaceIdMembersRoute =
  AuthenticatedSpacesSpaceIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedSpacesSpaceIdRoute,
  } as any)
const AuthenticatedSpacesSpaceIdInvitesRoute =
  AuthenticatedSpacesSpaceIdInvitesRouteImport.update({
    id: '/invites',
    path: '/invites',
    getParentRoute: () => AuthenticatedSpacesSpaceIdRoute,
  } as any)
const AuthenticatedSpacesSpaceIdPostsNewRoute =
  AuthenticatedSpacesSpaceIdPostsNewRouteImport.update({
    id: '/posts_/new',
    path: '/posts/new',
    getParentRoute: () => AuthenticatedSpacesSpaceIdRoute,
  } as any)
const AuthenticatedSpacesSpaceIdPostsPostIdRoute =
  AuthenticatedSpacesSpaceIdPostsPostIdRouteImport.update({
    id: '/posts_/$postId',
    path: '/posts/$postId',
    getParentRoute: () => AuthenticatedSpacesSpaceIdRoute,
  } as any)
const AuthenticatedSpacesSpaceIdPetsPetIdRoute =
  AuthenticatedSpacesSpaceIdPetsPetIdRouteImport.update({
    id: '/pets_/$petId',
    path: '/pets/$petId',
    getParentRoute: () => AuthenticatedSpacesSpaceIdRoute,
  } as any)
const AuthenticatedSpacesSpaceIdPostsPostIdEditRoute =
  AuthenticatedSpacesSpaceIdPostsPostIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedSpacesSpaceIdPostsPostIdRoute,
  } as any)
const AuthenticatedSpacesSpaceIdPetsPetIdEditRoute =
  AuthenticatedSpacesSpaceIdPetsPetIdEditRouteImport.update({
    id: '/pets_/$petId_/edit',
    path: '/pets/$petId/edit',
    getParentRoute: () => AuthenticatedSpacesSpaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/spaces': typeof AuthenticatedSpacesRoute
  '/invites/$inviteId': typeof AuthenticatedInvitesInviteIdRoute
  '/spaces/$spaceId': typeof AuthenticatedSpacesSpaceIdRouteWithChildren
  '/spaces/$spaceId/invites': typeof AuthenticatedSpacesSpaceIdInvitesRoute
  '/spaces/$spaceId/members': typeof AuthenticatedSpacesSpaceIdMembersRoute
  '/spaces/$spaceId/pets': typeof AuthenticatedSpacesSpaceIdPetsRoute
  '/spaces/$spaceId/posts': typeof AuthenticatedSpacesSpaceIdPostsRoute
  '/spaces/$spaceId/': typeof AuthenticatedSpacesSpaceIdIndexRoute
  '/spaces/$spaceId/pets/$petId': typeof AuthenticatedSpacesSpaceIdPetsPetIdRoute
  '/spaces/$spaceId/posts/$postId': typeof AuthenticatedSpacesSpaceIdPostsPostIdRouteWithChildren
  '/spaces/$spaceId/posts/new': typeof AuthenticatedSpacesSpaceIdPostsNewRoute
  '/spaces/$spaceId/pets/$petId/edit': typeof AuthenticatedSpacesSpaceIdPetsPetIdEditRoute
  '/spaces/$spaceId/posts/$postId/edit': typeof AuthenticatedSpacesSpaceIdPostsPostIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/spaces': typeof AuthenticatedSpacesRoute
  '/invites/$inviteId': typeof AuthenticatedInvitesInviteIdRoute
  '/spaces/$spaceId/invites': typeof AuthenticatedSpacesSpaceIdInvitesRoute
  '/spaces/$spaceId/members': typeof AuthenticatedSpacesSpaceIdMembersRoute
  '/spaces/$spaceId/pets': typeof AuthenticatedSpacesSpaceIdPetsRoute
  '/spaces/$spaceId/posts': typeof AuthenticatedSpacesSpaceIdPostsRoute
  '/spaces/$spaceId': typeof AuthenticatedSpacesSpaceIdIndexRoute
  '/spaces/$spaceId/pets/$petId': typeof AuthenticatedSpacesSpaceIdPetsPetIdRoute
  '/spaces/$spaceId/posts/$postId': typeof AuthenticatedSpacesSpaceIdPostsPostIdRouteWithChildren
  '/spaces/$spaceId/posts/new': typeof AuthenticatedSpacesSpaceIdPostsNewRoute
  '/spaces/$spaceId/pets/$petId/edit': typeof AuthenticatedSpacesSpaceIdPetsPetIdEditRoute
  '/spaces/$spaceId/posts/$postId/edit': typeof AuthenticatedSpacesSpaceIdPostsPostIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/spaces': typeof AuthenticatedSpacesRoute
  '/_authenticated/invites/$inviteId': typeof AuthenticatedInvitesInviteIdRoute
  '/_authenticated/spaces_/$spaceId': typeof AuthenticatedSpacesSpaceIdRouteWithChildren
  '/_authenticated/spaces_/$spaceId/invites': typeof AuthenticatedSpacesSpaceIdInvitesRoute
  '/_authenticated/spaces_/$spaceId/members': typeof AuthenticatedSpacesSpaceIdMembersRoute
  '/_authenticated/spaces_/$spaceId/pets': typeof AuthenticatedSpacesSpaceIdPetsRoute
  '/_authenticated/spaces_/$spaceId/posts': typeof AuthenticatedSpacesSpaceIdPostsRoute
  '/_authenticated/spaces_/$spaceId/': typeof AuthenticatedSpacesSpaceIdIndexRoute
  '/_authenticated/spaces_/$spaceId/pets_/$petId': typeof AuthenticatedSpacesSpaceIdPetsPetIdRoute
  '/_authenticated/spaces_/$spaceId/posts_/$postId': typeof AuthenticatedSpacesSpaceIdPostsPostIdRouteWithChildren
  '/_authenticated/spaces_/$spaceId/posts_/new': typeof AuthenticatedSpacesSpaceIdPostsNewRoute
  '/_authenticated/spaces_/$spaceId/pets_/$petId_/edit': typeof AuthenticatedSpacesSpaceIdPetsPetIdEditRoute
  '/_authenticated/spaces_/$spaceId/posts_/$postId/edit': typeof AuthenticatedSpacesSpaceIdPostsPostIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/spaces'
    | '/invites/$inviteId'
    | '/spaces/$spaceId'
    | '/spaces/$spaceId/invites'
    | '/spaces/$spaceId/members'
    | '/spaces/$spaceId/pets'
    | '/spaces/$spaceId/posts'
    | '/spaces/$spaceId/'
    | '/spaces/$spaceId/pets/$petId'
    | '/spaces/$spaceId/posts/$postId'
    | '/spaces/$spaceId/posts/new'
    | '/spaces/$spaceId/pets/$petId/edit'
    | '/spaces/$spaceId/posts/$postId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/spaces'
    | '/invites/$inviteId'
    | '/spaces/$spaceId/invites'
    | '/spaces/$spaceId/members'
    | '/spaces/$spaceId/pets'
    | '/spaces/$spaceId/posts'
    | '/spaces/$spaceId'
    | '/spaces/$spaceId/pets/$petId'
    | '/spaces/$spaceId/posts/$postId'
    | '/spaces/$spaceId/posts/new'
    | '/spaces/$spaceId/pets/$petId/edit'
    | '/spaces/$spaceId/posts/$postId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/spaces'
    | '/_authenticated/invites/$inviteId'
    | '/_authenticated/spaces_/$spaceId'
    | '/_authenticated/spaces_/$spaceId/invites'
    | '/_authenticated/spaces_/$spaceId/members'
    | '/_authenticated/spaces_/$spaceId/pets'
    | '/_authenticated/spaces_/$spaceId/posts'
    | '/_authenticated/spaces_/$spaceId/'
    | '/_authenticated/spaces_/$spaceId/pets_/$petId'
    | '/_authenticated/spaces_/$spaceId/posts_/$postId'
    | '/_authenticated/spaces_/$spaceId/posts_/new'
    | '/_authenticated/spaces_/$spaceId/pets_/$petId_/edit'
    | '/_authenticated/spaces_/$spaceId/posts_/$postId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/spaces': {
      id: '/_authenticated/spaces'
      path: '/spaces'
      fullPath: '/spaces'
      preLoaderRoute: typeof AuthenticatedSpacesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/spaces_/$spaceId': {
      id: '/_authenticated/spaces_/$spaceId'
      path: '/spaces/$spaceId'
      fullPath: '/spaces/$spaceId'
      preLoaderRoute: typeof AuthenticatedSpacesSpaceIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invites/$inviteId': {
      id: '/_authenticated/invites/$inviteId'
      path: '/invites/$inviteId'
      fullPath: '/invites/$inviteId'
      preLoaderRoute: typeof AuthenticatedInvitesInviteIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/spaces_/$spaceId/': {
      id: '/_authenticated/spaces_/$spaceId/'
      path: '/'
      fullPath: '/spaces/$spaceId/'
      preLoaderRoute: typeof AuthenticatedSpacesSpaceIdIndexRouteImport
      parentRoute: typeof AuthenticatedSpacesSpaceIdRoute
    }
    '/_authenticated/spaces_/$spaceId/posts': {
      id: '/_authenticated/spaces_/$spaceId/posts'
      path: '/posts'
      fullPath: '/spaces/$spaceId/posts'
      preLoaderRoute: typeof AuthenticatedSpacesSpaceIdPostsRouteImport
      parentRoute: typeof AuthenticatedSpacesSpaceIdRoute
    }
    '/_authenticated/spaces_/$spaceId/pets': {
      id: '/_authenticated/spaces_/$spaceId/pets'
      path: '/pets'
      fullPath: '/spaces/$spaceId/pets'
      preLoaderRoute: typeof AuthenticatedSpacesSpaceIdPetsRouteImport
      parentRoute: typeof AuthenticatedSpacesSpaceIdRoute
    }
    '/_authenticated/spaces_/$spaceId/members': {
      id: '/_authenticated/spaces_/$spaceId/members'
      path: '/members'
      fullPath: '/spaces/$spaceId/members'
      preLoaderRoute: typeof AuthenticatedSpacesSpaceIdMembersRouteImport
      parentRoute: typeof AuthenticatedSpacesSpaceIdRoute
    }
    '/_authenticated/spaces_/$spaceId/invites': {
      id: '/_authenticated/spaces_/$spaceId/invites'
      path: '/invites'
      fullPath: '/spaces/$spaceId/invites'
      preLoaderRoute: typeof AuthenticatedSpacesSpaceIdInvitesRouteImport
      parentRoute: typeof AuthenticatedSpacesSpaceIdRoute
    }
    '/_authenticated/spaces_/$spaceId/posts_/new': {
      id: '/_authenticated/spaces_/$spaceId/posts_/new'
      path: '/posts/new'
      fullPath: '/spaces/$spaceId/posts/new'
      preLoaderRoute: typeof AuthenticatedSpacesSpaceIdPostsNewRouteImport
      parentRoute: typeof AuthenticatedSpacesSpaceIdRoute
    }
    '/_authenticated/spaces_/$spaceId/posts_/$postId': {
      id: '/_authenticated/spaces_/$spaceId/posts_/$postId'
      path: '/posts/$postId'
      fullPath: '/spaces/$spaceId/posts/$postId'
      preLoaderRoute: typeof AuthenticatedSpacesSpaceIdPostsPostIdRouteImport
      parentRoute: typeof AuthenticatedSpacesSpaceIdRoute
    }
    '/_authenticated/spaces_/$spaceId/pets_/$petId': {
      id: '/_authenticated/spaces_/$spaceId/pets_/$petId'
      path: '/pets/$petId'
      fullPath: '/spaces/$spaceId/pets/$petId'
      preLoaderRoute: typeof AuthenticatedSpacesSpaceIdPetsPetIdRouteImport
      parentRoute: typeof AuthenticatedSpacesSpaceIdRoute
    }
    '/_authenticated/spaces_/$spaceId/posts_/$postId/edit': {
      id: '/_authenticated/spaces_/$spaceId/posts_/$postId/edit'
      path: '/edit'
      fullPath: '/spaces/$spaceId/posts/$postId/edit'
      preLoaderRoute: typeof AuthenticatedSpacesSpaceIdPostsPostIdEditRouteImport
      parentRoute: typeof AuthenticatedSpacesSpaceIdPostsPostIdRoute
    }
    '/_authenticated/spaces_/$spaceId/pets_/$petId_/edit': {
      id: '/_authenticated/spaces_/$spaceId/pets_/$petId_/edit'
      path: '/pets/$petId/edit'
      fullPath: '/spaces/$spaceId/pets/$petId/edit'
      preLoaderRoute: typeof AuthenticatedSpacesSpaceIdPetsPetIdEditRouteImport
      parentRoute: typeof AuthenticatedSpacesSpaceIdRoute
    }
  }
}

interface AuthenticatedSpacesSpaceIdPostsPostIdRouteChildren {
  AuthenticatedSpacesSpaceIdPostsPostIdEditRoute: typeof AuthenticatedSpacesSpaceIdPostsPostIdEditRoute
}

const AuthenticatedSpacesSpaceIdPostsPostIdRouteChildren: AuthenticatedSpacesSpaceIdPostsPostIdRouteChildren =
  {
    AuthenticatedSpacesSpaceIdPostsPostIdEditRoute:
      AuthenticatedSpacesSpaceIdPostsPostIdEditRoute,
  }

const AuthenticatedSpacesSpaceIdPostsPostIdRouteWithChildren =
  AuthenticatedSpacesSpaceIdPostsPostIdRoute._addFileChildren(
    AuthenticatedSpacesSpaceIdPostsPostIdRouteChildren,
  )

interface AuthenticatedSpacesSpaceIdRouteChildren {
  AuthenticatedSpacesSpaceIdInvitesRoute: typeof AuthenticatedSpacesSpaceIdInvitesRoute
  AuthenticatedSpacesSpaceIdMembersRoute: typeof AuthenticatedSpacesSpaceIdMembersRoute
  AuthenticatedSpacesSpaceIdPetsRoute: typeof AuthenticatedSpacesSpaceIdPetsRoute
  AuthenticatedSpacesSpaceIdPostsRoute: typeof AuthenticatedSpacesSpaceIdPostsRoute
  AuthenticatedSpacesSpaceIdIndexRoute: typeof AuthenticatedSpacesSpaceIdIndexRoute
  AuthenticatedSpacesSpaceIdPetsPetIdRoute: typeof AuthenticatedSpacesSpaceIdPetsPetIdRoute
  AuthenticatedSpacesSpaceIdPostsPostIdRoute: typeof AuthenticatedSpacesSpaceIdPostsPostIdRouteWithChildren
  AuthenticatedSpacesSpaceIdPostsNewRoute: typeof AuthenticatedSpacesSpaceIdPostsNewRoute
  AuthenticatedSpacesSpaceIdPetsPetIdEditRoute: typeof AuthenticatedSpacesSpaceIdPetsPetIdEditRoute
}

const AuthenticatedSpacesSpaceIdRouteChildren: AuthenticatedSpacesSpaceIdRouteChildren =
  {
    AuthenticatedSpacesSpaceIdInvitesRoute:
      AuthenticatedSpacesSpaceIdInvitesRoute,
    AuthenticatedSpacesSpaceIdMembersRoute:
      AuthenticatedSpacesSpaceIdMembersRoute,
    AuthenticatedSpacesSpaceIdPetsRoute: AuthenticatedSpacesSpaceIdPetsRoute,
    AuthenticatedSpacesSpaceIdPostsRoute: AuthenticatedSpacesSpaceIdPostsRoute,
    AuthenticatedSpacesSpaceIdIndexRoute: AuthenticatedSpacesSpaceIdIndexRoute,
    AuthenticatedSpacesSpaceIdPetsPetIdRoute:
      AuthenticatedSpacesSpaceIdPetsPetIdRoute,
    AuthenticatedSpacesSpaceIdPostsPostIdRoute:
      AuthenticatedSpacesSpaceIdPostsPostIdRouteWithChildren,
    AuthenticatedSpacesSpaceIdPostsNewRoute:
      AuthenticatedSpacesSpaceIdPostsNewRoute,
    AuthenticatedSpacesSpaceIdPetsPetIdEditRoute:
      AuthenticatedSpacesSpaceIdPetsPetIdEditRoute,
  }

const AuthenticatedSpacesSpaceIdRouteWithChildren =
  AuthenticatedSpacesSpaceIdRoute._addFileChildren(
    AuthenticatedSpacesSpaceIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedSpacesRoute: typeof AuthenticatedSpacesRoute
  AuthenticatedInvitesInviteIdRoute: typeof AuthenticatedInvitesInviteIdRoute
  AuthenticatedSpacesSpaceIdRoute: typeof AuthenticatedSpacesSpaceIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSpacesRoute: AuthenticatedSpacesRoute,
  AuthenticatedInvitesInviteIdRoute: AuthenticatedInvitesInviteIdRoute,
  AuthenticatedSpacesSpaceIdRoute: AuthenticatedSpacesSpaceIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
