name = "belu-api"
main = "src/index.ts"
compatibility_date = "2026-07-05"
compatibility_flags = ["nodejs_compat"]

[vars]
APP_ENV = "development"
AUTH_BASE_URL = "http://localhost:8787"
AUTH_TRUSTED_ORIGINS = "http://localhost:5173"
R2_ACCOUNT_ID = "4e53d433fc24972cc26967a37a439d62"
R2_BUCKET_NAME = "belu-photos-dev"

[[d1_databases]]
binding = "DB"
database_name = "belu-local"
database_id = "local"
migrations_dir = "drizzle/migrations"

[[r2_buckets]]
binding = "PHOTOS_BUCKET"
bucket_name = "belu-photos-dev"

[env.dev]
name = "belu-api-dev"

[env.dev.vars]
APP_ENV = "development"
AUTH_BASE_URL = "https://belu-api-dev.shantianlongxing20.workers.dev"
AUTH_TRUSTED_ORIGINS = "https://belu-web-dev.shantianlongxing20.workers.dev"
R2_ACCOUNT_ID = "4e53d433fc24972cc26967a37a439d62"
R2_BUCKET_NAME = "belu-photos-dev"

[[env.dev.d1_databases]]
binding = "DB"
database_name = "belu-dev"
database_id = "2ffb40e4-a176-49ad-aba9-c3db06de21c9"
migrations_dir = "drizzle/migrations"

[[env.dev.r2_buckets]]
binding = "PHOTOS_BUCKET"
bucket_name = "belu-photos-dev"
