name = "belu-api"
main = "src/index.ts"
compatibility_date = "2026-07-05"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "belu-local"
database_id = "local"
migrations_dir = "drizzle/migrations"
